WALL_TIMEOUT = 2400
TIMEOUT = 2399
EXTRA_CAP = True
EXTRA_MAX = 1000
SMTLIB_BENCHMARKS_DB = 'benchmarks'
LIB_DIR = 'lib'
RESULTS_DIR = 'results'
SAVE_DB = True
USE_GRAMMATICAL_CONSTRUCT_FEATURES = True
FEATURE_CALC_TIMEOUT = 1.0
N_PCA_COMPONENTS = 30

EVAL_YEAR = 2019

import multiprocessing
CORES = 12

MIN_DATA_POINTS=25

K_FOLD = 2 ## a number or 'all' to do all against one
# CORES = 1