WALL_TIMEOUT = 2400
TIMEOUT = 2399
EXTRA_CAP = True
EXTRA_MAX = 1000
SMTLIB_BENCHMARKS_DB = 'benchmarks'
LIB_DIR = 'lib'
RESULTS_DIR = 'results'
SAVE_DB = True
USE_GRAMMATICAL_CONSTRUCT_FEATURES = True
FEATURE_CALC_TIMEOUT = 1.0

import multiprocessing
CORES = multiprocessing.cpu_count() * 2

K_FOLD = 10
# CORES = 1