WALL_TIMEOUT = 2400
SMTLIB_BENCHMARKS_DB = 'benchmarks'
LIB_DIR = 'lib'
RESULTS_DIR = 'results'
SAVE_DB = True
USE_GRAMMATICAL_CONSTRUCT_FEATURES = True
FEATURE_CALC_TIMEOUT = 1.0


EVAL_YEAR = 2019

WALL=False